services:
  postgres:
    image: postgres
    container_name: postgressql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  clientapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
networks:
  mynetwork:
    external: true
volumes:
  postgres-data: